### ISSUE TITLE
apacman no more available on AUR

### ISSUE THREAD

**Issue by julianxhokaxhiu** [oshazard/apacman#102]
Hi,

I was updating as always my platform this morning and I found out that apacman is now throwing an error saying that `apacman is not found`.

So I was trying to search for it on the AUR and I found nothing.

What happened to your package? Did you remove it?

Best regards,
Julian

**Comment by lectrode** [comment]
Hi julian, saw ur `apacman-git` in the AUR. Just disappeared within the last hour. Any idea what happened to it?

**Comment by julianxhokaxhiu** [comment]
Was removed by the community. It was reported as dead project, discontinued and seems to no be compliant with AURv4.

Would be nice to have some feedback from the author.

**Comment by simon04** [comment]
It got deleted twice in a row: https://mail-archive.com/aur-requests@archlinux.org/msg20762.html and https://mail-archive.com/aur-requests@archlinux.org/msg20766.html

It's funny that the even older wrapper `packer` and the source of this fork is still in AUR: https://aur.archlinux.org/packages/packer/

Btw: I'll move to https://github.com/Jguer/yay

**Comment by jordan-000** [comment]
Is there any fix for this? I'm unable to install apacman

**Comment by lectrode** [comment]
you can still install it with the following:
```
git clone https://aur.archlinux.org/apacman.git
cd apacman
makepkg -si
```

You can do something similar with `apacman-deps` and `apacman-utils` should you want them.

**Comment by jordan-000** [comment]
Thank you so much!

**Comment by autoferrit** [comment]
I still get an error with this
```bash
$ apacman -Suu
:: Starting full system upgrade...
 there is nothing to do
:: Synchronizing aur database...
 aur                                                              1  1 [#######################################] 100%:: Starting full aur upgrade...

Unresolvable   (1): apacman
```

This is on a fresh install of arch.

**Comment by tobixen** [comment]
One month now without any official statement from the maintainer of the package.  It would at least be interesting to know if the reason is lack of time or because the maintainer has given up on this package.

There are [quite many alternative tools](https://wiki.archlinux.org/index.php/AUR_helpers) out there for installing AUR-packages, the question probably is which one to convert to.

As mentioned above, if apacman is deprecated, then that applies to packer as well.  packer clearly isn't maintained at all.  I'll just follow in the footsteps of @simon04 and install [yay](https://github.com/Jguer/yay), using `apacman -S yay`.

Post-edit: So far I'm happy with yay, the user experience is better.  I recommend it.

**Comment by lectrode** [comment]
> There are quite many alternative tools out there for installing AUR-packages, the question probably is which one to convert to.

AFAIK, there is only one AUR management tool that you can successfully run/execute as root, and that is `apacman`. This is functionality I rely on to update the many computers I manage without having to touch each one individually. Otherwise, moving to an actively maintained AUR package manager would be swell.

I created a [request](https://github.com/Jguer/yay/issues/69) in the issue tracker for yay to request this functionality. Anyone else who relies on this functionality is welcome to comment on it.

> I still get an error with this

The commands I posted above allow you to install it, but because it is still not in the AUR or any other repository, it will be unresolvable. It is currently not receiving updates anyway. If at some point in the future it is added to a repository, it will no longer be unresolvable and will pull updates like any other package.

**Comment by tobixen** [comment]
Wouldn't "sudo -u nobody yay -Suy" do?

**Comment by lectrode** [comment]
```
# sudo -u nobody yay -Syu
Unable to create config directory: /.config/yay mkdir /.config: permission denied
```
Command was run as root

EDIT:
Tried with `yaourt` and `packer` and It works...except that it still asks for root password when it attempts to install it. I'd have to do that manually for each computer...which isn't feasible.

I have a script that is executed by a systemd service (run as root) that updates all packages. The script is not interactive, so it needs to be able to execute everything without needing to enter credentials. It already has root permissions, hence the need to run as root. `apacman` is the only package manager I've found that has this ability.

**Comment by julianxhokaxhiu** [comment]
It seems that the author is not willing to work on it and support the new AUR API.

I would then close this issue, and suggest to move on to any other AUR manager.

Thank you all for the support on this.

**Comment by jordan-000** [comment]
Moved to trizen

**Comment by lectrode** [comment]
FYI: there's a new alternate AUR helper that can be run as root (or with `su`): [`pikaur`](https://github.com/actionless/pikaur).
