### ISSUE TITLE
NOTICE: removal of --pkg from makepkg

### ISSUE THREAD

**Issue by oshazard** [oshazard/apacman#32]
On the *pacman-dev* mailing list, the next version of `makepkg` is removing the *--pkg* flag, which means that in the case of split packages, all packages must be built.

**Read more:** https://lists.archlinux.org/pipermail/pacman-dev/2015-September/020353.html

**Comment by oshazard** [comment]
Since not many people read the mailing list, I'm going tag some users who have previously contributed.
* @bts368
* @rmarquis
* @senorsmile
* @suedi
* @helixarch

Any thoughts?

**Comment by helixarch** [comment]
Is this official?

**Comment by oshazard** [comment]
**Allan** is the main developer for `pacman` and `makepkg`, so yeah it would seem to. 
[First post in thread](https://lists.archlinux.org/pipermail/pacman-dev/2015-September/020347.html), then just keep clicking on the *next* link. 
Not sure when this change will hit the repos though.

**Comment by rmarquis** [comment]
A contributor [notified me](https://github.com/rmarquis/pacaur/issues/364) yesterday about it. It's hard to say in which extend this change has an impact to helpers, as it will be combined with a "[rpm packaging style](https://lists.archlinux.org/pipermail/pacman-dev/2015-September/020350.html)".

In any case, all split subpackages will need to be built, but we might still be able to install only a specific one.

**Comment by bts368** [comment]
I really am losing faith in Allan. He keeps making some bad decisions in my playbook. He keeps doing this like this. "Oh, it's broken? I'll just remove it instead of fixing it."

Regardless.

That aside, split packages were already building the entire package set with apacman (https://github.com/oshazard/apacman/issues/14), at least up until very recently (I haven't tested 2.x yet with split packages). I guess Allen's just trying to edge split packages out of usage altogether, honestly, as I can't see any proper justification for doing this.

**Comment by rmarquis** [comment]
@bts368 The removal of the --pkg feature only makes sense in light on the "rpm packaging style", as mentioned in the mailing list. This part is not implemented yet.

**Comment by suedi** [comment]
I have no memory of using --pkg 

Is it important for apacman internally?

**Comment by oshazard** [comment]
Removed / resolved in #61
